name: flutter_paystack_tk
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.2
homepage: https://github.com/DeTuksa/flutter_paystack_tk

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  intl: ^0.18.0
  meta: ^1.8.0
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.12
  mockito: ^5.3.1


flutter:
  plugin:
    platforms:
      android:
        package: tk.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"
